spring:
  client:
    serviceUrl:
      defaultZone: http://localhost:6001/eureka/
  cloud:
    gateway:
      routes:
        - id: microservice-formateur
          uri: lb://formateur
          predicates:
          - Path=/formateur/**
          filters:
          - RewritePath=/formateur/(?<path>.*), /$\{path}  
        - id: microservice-cours
          uri: lb://cours
          predicates:
          - Path=/cours/**
          filters:
          - RewritePath=/cours/(?<path>.*), /$\{path}    
               